export const projects = [
  {
    num: "01",
    category: "Real-time Communication",
    name: "NawaNapam",
    image: "/files/nawanapam.png",
    github: "https://github.com/NawaNapam/nawanapam-core",
    live: "https://www.nawanapam.com/",
    desc: "Real-time, one-to-one communication platform serving 5,000+ registered users, with a Redis-based matchmaking engine (Lua scripting, heartbeat tracking, session persistence) and RBAC/moderation APIs on PostgreSQL and Prisma.",
  },
  {
    num: "02",
    category: "Distributed Job Scheduling",
    name: "Zan",
    image: "/files/zan.png",
    github: "https://github.com/pandarudra/Zan",
    live: "https://zan-web.vercel.app/",
    desc: "Distributed job-scheduling backend for a decentralized compute marketplace, using Redis and BullMQ for task orchestration and execution tracking, Azure Blob Storage, and an Electron desktop app for machine onboarding.",
  },
  {
    num: "03",
    category: "Full Stack Platform",
    name: "Hostify",
    image: "/files/hostify.png",
    github: "https://github.com/pandarudra/hostify",
    live: "https://hostify.rudrax.me/",
    desc: "A full-stack static site hosting platform with one-click GitHub deployments and custom subdomains.",
  },
  {
    num: "04",
    category: "Real-time Collab",
    name: "Draw.wine",
    image: "/files/draw-wine.png",
    github: "https://github.com/pandarudra/draw.wine",
    live: "https://draw-wine.rudrax.me/",
    desc: "Real-time collaborative whiteboard with Gemini AI integration, Socket.IO, and Solana wallet auth.",
  },
  {
    num: "05",
    category: "Management System",
    name: "Inventra",
    image: "/files/ims.png",
    github: "https://github.com/pandarudra/ims",
    live: "https://ims.rudrax.me/",
    desc: "Inventory management system with streamlined product tracking, stock handling, and modern dashboard workflows.",
  },

  {
    num: "06",
    category: "File Sharing",
    name: "Zipster",
    image: "/files/zipster.png",
    github: "https://github.com/pandarudra/Zipster",
    live: "https://zipster-alpha.vercel.app",
    desc: "Fast and minimal file sharing platform focused on secure uploads, instant transfers, and clean user experience.",
  },

  {
    num: "07",
    category: "Real-time Chat",
    name: "ChitChat",
    image: "/files/chitchat.png",
    github: "https://github.com/pandarudra/chitchat",
    live: "",
    desc: "Real-time chat application built with modern web technologies featuring instant messaging and responsive UI.",
  },
];
