export const projects = [
  {
    num: "01",
    category: "Email Client",
    name: "TrueMail",
    image: "/files/truemail.png",
    github: "https://github.com/pandarudra/true-mail",
    live: "https://true-mail-one.vercel.app/",
    desc: "Modern email client on your own Resend account and custom domain, with threading, multiple mailboxes, AI summaries and action items, tasks, and a calendar, with credentials encrypted at rest.",
    problem:
      "Most inboxes lock you into someone else's infrastructure; TrueMail gives you a modern inbox on top of email you actually own (your domain, your Resend account).",
    features: [
      "Custom domain setup with SPF/DKIM/DMARC verification",
      "Bring-your-own Resend account via OAuth, credentials encrypted at rest and used server-side only",
      "Multiple mailboxes on one domain",
      "Full inbox: labels, search, starred, archive, spam, trash, autosaving drafts",
      "Reply, reply-all, forward and attachments",
      "Built-in tasks with due dates, priorities, subtasks and recurring reminders",
      "Calendar with country holidays and event detection from emails",
      "Optional AI assist: email summaries, reply drafting, inbox Q&A, action-item extraction",
      "Optional Telegram assistant for daily summary, tasks and calendar",
    ],
    stack: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Prisma",
      "PostgreSQL",
      "better-auth",
      "Resend",
      "Cloudinary",
      "Tailwind CSS v4",
      "Vitest",
    ],
  },
  {
    num: "02",
    category: "Real-time Communication",
    name: "NawaNapam",
    image: "/files/nawanapam.png",
    github: "https://github.com/NawaNapam/nawanapam-core",
    live: "https://www.nawanapam.com/",
    desc: "Real-time, one-to-one communication platform serving 5,000+ registered users, with a Redis-based matchmaking engine (Lua scripting, heartbeat tracking, session persistence) and RBAC/moderation APIs on PostgreSQL and Prisma.",
    problem:
      "Lets two strangers start a live video conversation instantly, with no profile required and privacy built in.",
    features: [
      "Peer-to-peer HD video and audio via WebRTC with live text chat",
      "Redis-backed matchmaking queue with sub-3-second match-to-connect",
      "Socket.IO signaling with heartbeat liveness checks and auto re-match",
      "Anonymous sessions plus Email/OTP and Google OAuth",
      "Reporting, moderation logs, user bans and an admin console",
      "Android app via Capacitor with push notifications",
    ],
    stack: [
      "Next.js",
      "React 19",
      "TypeScript",
      "Express 5",
      "Socket.IO",
      "WebRTC",
      "Redis",
      "PostgreSQL",
      "Prisma",
      "NextAuth.js",
      "Capacitor",
    ],
  },
  {
    num: "03",
    category: "Distributed Job Scheduling",
    name: "Zan",
    image: "/files/zan.png",
    github: "https://github.com/pandarudra/Zan",
    live: "https://zan-web.vercel.app/",
    desc: "Distributed job-scheduling backend for a decentralized compute marketplace, using Redis and BullMQ for task orchestration and execution tracking, Azure Blob Storage, and an Electron desktop app for machine onboarding.",
    problem:
      "Connects people who need GPU compute with providers who have idle machines, as a decentralized compute marketplace.",
    features: [
      "Web client for job submission",
      "API server with Redis and BullMQ job orchestration and execution tracking",
      "Electron provider agent for machine onboarding",
      "Azure Blob Storage for job artifacts",
      "Solana programs and a TypeScript SDK in a pnpm/Turbo monorepo",
    ],
    stack: [
      "TypeScript",
      "Next.js",
      "Express",
      "Redis",
      "BullMQ",
      "Prisma",
      "Electron",
      "Azure Blob Storage",
      "Solana",
    ],
  },
  {
    num: "04",
    category: "Full Stack Platform",
    name: "Hostify",
    image: "/files/hostify.png",
    github: "https://github.com/pandarudra/hostify",
    live: "https://hostify.rudrax.me/",
    desc: "A full-stack static site hosting platform with one-click GitHub deployments and custom subdomains.",
    problem:
      "Self-hosted alternative to Vercel/Netlify for static sites: deploy from GitHub with full control over hosting.",
    features: [
      "One-click deploys from public GitHub repositories",
      "Auto-redeploy on push via GitHub webhooks",
      "Custom or auto-generated subdomains routed through Cloudflare KV",
      "GitHub OAuth login",
      "Dashboard with deployment history and status",
    ],
    stack: [
      "SvelteKit",
      "TypeScript",
      "Express.js",
      "MongoDB",
      "Azure Blob Storage",
      "Cloudflare KV",
      "Tailwind CSS",
      "Docker",
      "Playwright",
    ],
  },
  {
    num: "05",
    category: "Real-time Collab",
    name: "Draw.wine",
    image: "/files/draw-wine.png",
    github: "https://github.com/pandarudra/draw.wine",
    live: "https://draw-wine.rudrax.me/",
    desc: "Real-time collaborative whiteboard with Gemini AI integration, Socket.IO, and Solana wallet auth.",
    problem:
      "A shared whiteboard where several people can sketch and diagram together in real time.",
    features: [
      "Room-based multiplayer drawing with live cursor sync",
      "Shape, text, image, arrow, eraser and laser-pointer tools",
      "Export/import PNG, JPG, SVG, JSON and Mermaid diagrams",
      "Gemini-powered AI drawing generation",
      "Email room invitations",
      "Installable PWA",
    ],
    stack: [
      "React",
      "Vite",
      "TypeScript",
      "Express",
      "Socket.IO",
      "Redis Pub/Sub",
      "Google Gemini",
      "Solana wallet auth",
    ],
  },
  {
    num: "06",
    category: "Management System",
    name: "Inventra",
    image: "/files/ims.png",
    github: "https://github.com/pandarudra/ims",
    live: "https://ims.rudrax.me/",
    desc: "Inventory management system with streamlined product tracking, stock handling, and modern dashboard workflows.",
    problem:
      "Tracks inventory for an organization with role-specific access and approval workflows instead of spreadsheets.",
    features: [
      "Role-based dashboards for Admin, Manager and Staff",
      "Multi-tier approval workflows for maintenance, repair and procurement",
      "In-app notifications and low-stock alerts",
      "Light/dark mode",
      "Dockerized local and production stacks behind Nginx",
    ],
    stack: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "Recharts",
      "MongoDB",
      "Docker",
      "Nginx",
    ],
  },

  {
    num: "07",
    category: "File Compression",
    name: "Zipster",
    image: "/files/zipster.png",
    github: "https://github.com/pandarudra/Zipster",
    live: "https://zipster-alpha.vercel.app",
    desc: "Browser-based file compression and decompression powered by a C++ Huffman coding implementation compiled to WebAssembly.",
    problem:
      "Compress and decompress files in the browser using a from-scratch Huffman coding implementation.",
    features: [
      "Huffman coding written in C++ and compiled to WebAssembly",
      "Compression and decompression with drag-and-drop upload",
      "Compression ratio and size statistics",
      "Live progress tracking",
      "Dark mode",
    ],
    stack: [
      "C++",
      "WebAssembly (Emscripten)",
      "Next.js 15",
      "React 19",
      "Tailwind CSS",
      "Radix UI",
    ],
  },

  {
    num: "08",
    category: "Real-time Chat",
    name: "ChitChat",
    image: "/files/chitchat.png",
    github: "https://github.com/pandarudra/chitchat",
    live: "",
    desc: "Real-time chat platform with media messaging, WebRTC voice and video calls, and Gemini-powered AI replies.",
    problem:
      "A single app for messaging, voice/video calls and AI replies between contacts.",
    features: [
      "Real-time messaging with text, images, video, audio and files",
      "Read receipts and typing indicators",
      "WebRTC video and audio calls with screen share",
      "OTP phone authentication with JWT refresh tokens",
      "Google Gemini AI responses",
      "Contact management with block and online status",
    ],
    stack: [
      "React",
      "TypeScript",
      "Express",
      "Socket.IO",
      "WebRTC",
      "MongoDB",
      "Redis",
      "Cloudinary",
      "Google Gemini",
    ],
  },

  {
    num: "09",
    category: "Security / CLI",
    name: "ECRYPTO",
    image: "/files/ecrypto.png",
    github: "https://github.com/pandarudra/ecrypto",
    live: "https://pandarudra.github.io/ecrypto/",
    desc: "Go tool that encrypts folders into a single tamper-proof .ecrypt container using XChaCha20-Poly1305 and Argon2id, with passphrase or key-file modes and tunable security parameters.",
    problem:
      "Encrypts whole folders, including filenames and metadata, into one tamper-proof file protected by modern cryptography.",
    features: [
      "XChaCha20-Poly1305 authenticated encryption with 256-bit keys",
      "Argon2id key derivation from passphrases, or raw 32-byte key files",
      "Compresses and encrypts folders into a single .ecrypt container",
      "Tamper detection via authentication tags",
      "Interactive file browser and a scriptable CLI",
      "Single cross-platform binary for Windows, macOS and Linux, also on npm",
    ],
    stack: ["Go", "XChaCha20-Poly1305", "Argon2id"],
  },
];
